COPY INTO RETAIL.RAW.RAW_INVOICES
FROM @RETAIL.RAW.RETAIL_STAGE/Online_Retail.csv.gz
FILE_FORMAT = (TYPE=CSV FIELD_OPTIONALLY_ENCLOSED_BY='"' SKIP_HEADER=1
               RECORD_DELIMITER='\r' ENCODING='ISO-8859-1')
ON_ERROR = 'ABORT_STATEMENT'
FORCE = TRUE;  -- Bypass load history since table is truncated first
